name: CI/CD Pipeline with Selenium Tests

# Trigger workflow on push to the 'main' branch or pull requests to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow

jobs:
  selenium-tests:
    runs-on: windows-latest

    # Set up job steps
    steps:
      # 1. Checkout the repository to get the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      # 3. Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Pytest tests
      - name: Run Pytest tests
        run: |
          pytest --maxfail=5 --disable-warnings --alluredir=reports/allure-results

      # 5. Upload Allure test results
      - name: Upload Allure Test Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      # 6. Upload Pytest HTML report
      - name: Upload Pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/pytest_html_report.html

      # 7. Upload logs for debugging
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: reports/logs/  # Upload the log files for debugging
