name: CI/CD Pipeline with Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-chrome:
    name: Run Tests on Chrome
    runs-on: windows-latest
    timeout-minutes: 30

    env:
      BROWSER: chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest with Allure (Chrome)
        run: |
          pytest -n auto --disable-warnings --alluredir=reports/allure-results --html=reports/pytest_html_report.html --self-contained-html

      - name: Upload Allure Results (Chrome)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-chrome
          path: reports/allure-results

      - name: Upload Pytest HTML Report (Chrome)
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-chrome
          path: reports/pytest_html_report.html

      - name: Upload Logs (Chrome)
        uses: actions/upload-artifact@v4
        with:
          name: logs-chrome
          path: reports/logs/

  test-firefox:
    name: Run Tests on Firefox
    runs-on: windows-latest
    timeout-minutes: 30

    env:
      BROWSER: firefox

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest with Allure (Firefox)
        run: |
          pytest -n auto --disable-warnings --alluredir=reports/allure-results --html=reports/pytest_html_report.html --self-contained-html

      - name: Upload Allure Results (Firefox)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-firefox
          path: reports/allure-results

      - name: Upload Pytest HTML Report (Firefox)
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-firefox
          path: reports/pytest_html_report.html

      - name: Upload Logs (Firefox)
        uses: actions/upload-artifact@v4
        with:
          name: logs-firefox
          path: reports/logs/
